const config = {
  NODE_ENV: process.env.NODE_ENV || "production",
  KEY: process.env.REACT_APP_RAPIDAPI_KEY,
  CRYPTO_CURRENCIES_API_URL: process.env.REACT_APP_CRYPTO_API_URL,
  CRYPTO_NEWS_API_URL: process.env.REACT_APP_NEWS_API_URL,
  CRYPTO_CURRENCIES_HOST: process.env.REACT_APP_CRYPTO_RAPIDAPI_HOST,
  CRYPTO_NEWS_HOST: process.env.REACT_APP_NEWS_RAPIDAPI_HOST,
};

export const {
    NODE_ENV,
    KEY,
    CRYPTO_CURRENCIES_API_URL,
    CRYPTO_NEWS_API_URL,
    CRYPTO_NEWS_HOST,
    CRYPTO_CURRENCIES_HOST
} = config
