export { default as Navbar } from "./NavBar"
export { default as CryptoCurrencies } from "./CryptoCurrencies"
export { default as Home } from "./Home"
export { default as News } from "./News"
export { default as Exchanges } from "./Exchanges"
export { default as CryptoDetails } from "./CryptoDetails"